#!/bin/sh

version=$(git describe --abbrev=0 --tags)
name="ledger-$version-x86_64-unknown-linux-gnu"

mkdir -p ./builds/
cargo build --release
rm -rf "/tmp/$name"
mkdir "/tmp/$name"
cp ./target/release/ledger "/tmp/$name/"
cp ./README.md "/tmp/$name/"
cp ./LICENSE "/tmp/$name/"
tar zcf "./builds/$name.tar.gz" -C /tmp $name
cd ./builds
sha256sum "$name.tar.gz" > "$name-sha256sum.txt"
cd -
